name: IME同步到gitee镜像
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITEE_USER: xzy_nine
      GITEE_ORG: xzy-ime
      GITEE_API: https://gitee.com/api/v5
      GITHUB_API: https://api.github.com
      PARALLEL_JOBS: 4
      MY_GITEE_PAT: ${{ secrets.MY_GITEE_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y jq

      - name: Configure git
        run: |
          git config --global user.name "yang"
          git config --global user.email "xzyht-nine@outlook.com"

      - name: Run mirror sync
        run: bash sync.sh IME/repo-map.json
